### ISSUE TITLE
Regarding Trained Transformer download

### ISSUE THREAD

**Issue by spprabhu** [zomux/lanmt#3]
Hi Raphael I am unable to download the Trained Transformer , I am getting this issue

wget https://drive.google.com/file/d/1xB81cmSQ7l66zZjWPEBhoc4nzjgFSWZW/view lanmt_teacher_models.tgz
--2019-11-29 10:56:50--  https://drive.google.com/file/d/1xB81cmSQ7l66zZjWPEBhoc4nzjgFSWZW/view
Resolving drive.google.com (drive.google.com)... 172.217.4.78, 2607:f8b0:4009:800::200e
Connecting to drive.google.com (drive.google.com)|172.217.4.78|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘view.2’

view.2                                   [ <=>                                                                  ]  66.43K  --.-KB/s    in 0.04s   

2019-11-29 10:56:50 (1.72 MB/s) - ‘view.2’ saved [68021]

--2019-11-29 10:56:50--  http://lanmt_teacher_models.tgz/
Resolving lanmt_teacher_models.tgz (lanmt_teacher_models.tgz)... failed: Name or service not known.
wget: unable to resolve host address ‘lanmt_teacher_models.tgz’
FINISHED --2019-11-29 10:56:50--
Total wall clock time: 0.3s
Downloaded: 1 files, 66K in 0.04s (1.72 MB/s)

**Comment by zomux** [comment]
@spprabhu Please follow the instructions. `wget` won't work for google drive.

```
./gdown.pl https://drive.google.com/file/d/1xB81cmSQ7l66zZjWPEBhoc4nzjgFSWZW/view lanmt_teacher_models.tgz
tar xzvf lanmt_teacher_models.tgz
```

**Comment by spprabhu** [comment]
Hi Thanks for fast reply,Got it
