### ISSUE TITLE
Regarding Speed on SIngle GPU and Training Configurations

### ISSUE THREAD

**Issue by spprabhu** [zomux/lanmt#4]
Hi Raphael Can you please share Times for single and Multi-Gpus as well as their configurations

**Comment by zomux** [comment]
@spprabhu Hi, all the decoding times on the github page https://github.com/zomux/lanmt#summary-of--results are measured on Single V100 GPU. The decoding code does't support multiple GPUs.

**Comment by spprabhu** [comment]
Also whats the training Time.

**Comment by spprabhu** [comment]
Also can you please Specify the CPU RAM Requirements.

**Comment by spprabhu** [comment]
My TRaining is getting killed because of complete utilization of CPU RAM.I am g4 instance which have Tesla T4 GPUs.

**Comment by spprabhu** [comment]
Hi Raphael kind please share your training configuration details.Also PLease share how to convert the dataset extension in the format I want from .sp to my specific format.
Also for this what changes will I need to make in my Code where and in which file.So it is also compatible during inference.

**Comment by zomux** [comment]
Hi, the training script may consume CPU memory as it preload all the text files into onboard memory before training.

**Comment by zomux** [comment]
In my environment, I train my models on 8 V100 GPUs with NVLink2 available.

**Comment by zomux** [comment]
How large is your corpus?

**Comment by zomux** [comment]
".sp" files are text files tokenized by sentencepiece.

**Comment by spprabhu** [comment]
My Corpus is as large as EN-DE Training set.Also can we send the training data in Batches .

**Comment by zomux** [comment]
My implementation in `MTDataset` loaded all text on to the memory. So may be it is not memory friendly. I don't know whether you can upgrade the memory size
